version: '3.3'
services: 
        db:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_DATABASE: 'db'
                        MYSQL_USER: 'user'
                        MYSQL_PASSWORD: 'password'
                        MYSQL_ROOT_PASSWORD: 'password'
                ports: 
                        - '3306:3306'
                expose:
                        - '3306'

                volumes:
                        - my-db:/var/lib/mysql
        server:
                build: ./server
                restart: always
                ports:
                        - '5000:5000'
                expose:
                        - '5000'
        client:
                build: ./client
                restart: always
                stdin_open: true
                tty: true
        
        app-admin:
                build: ./app-admin
                restart: always
                stdin_open: true
                tty: true

                

volumes:
        my-db:
        
